services:
  piston:
    image: ghcr.io/engineer-man/piston
    container_name: fara-piston
    restart: unless-stopped
    privileged: true
    ports:
      - "2000:2000"
    volumes:
      - piston-packages:/piston/packages

volumes:
  piston-packages:
